config/routes.rb
Rails.application.routes.draw do

  resources :roads, only: [:index,:show]

  resources :reports, only: [:index] do
    resources :profiles, only: [:show,:index]
  end

  get '/profiles/:id/history', to: 'profiles#history'

  resources :people

  root to: 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.fetch(:person, {})
    end
end

app/controllers/profiles_controller.rb
require "parquet"

class ProfilesController < ApplicationController

  def index
    table = Arrow::Table.load("#{Rails.root}/public/reports/#{params[:report_id]}.parquet")
    @ci = table["cluster_id"].to_a.uniq
    render json: {data: @ci.map{|t| t.split(".").first}}
  end

  def history

    id = params[:id]
    @profiles = Dir.glob(Rails.root.join('public', 'gruff_images','*')).map{|t| {name: t.split("/").last.split(".").first}}
    @profiles = Dir.glob(Rails.root.join('public', 'gruff_images','*')).map{|t| {name: t.split("/").last.split(".").first}}

    @profiles = @profiles.map{|t| (t[:name].split("__").last == id ? t[:name] : nil)}
    @profiles.delete(nil)

    render json: {data: @profiles.uniq.sort()}

  end


  def show

    table = Arrow::Table.load("#{Rails.root}/public/reports/#{params[:report_id]}.parquet")

    count = table.size

    @xy = []

    i = 1

    rh = table["restored_height"].to_a
    cd = table["current_distance"].to_a
    ci = table["cluster_id"].to_a

    min_h = nil
    max_h = nil

    min_d = nil
    max_d = nil

    while i < count - 1

      if rh[i].present? && cd[i].present? && ci[i] == "#{params[:id]}.csv"

        if (min_h.to_f > rh[i] && rh[i] != 0) || min_h == nil
          min_h = rh[i]
        end
        if (max_h.to_f < rh[i] && rh[i] != 0) || max_h == nil
          max_h = rh[i]
        end
        if (min_d.to_f > cd[i] && cd[i] != 0) || min_d == nil
          min_d = cd[i]
        end
        if (max_d.to_f < cd[i] && cd[i] != 0) || max_d == nil
          max_d = cd[i]
        end

        h = rh[i]
        d = cd[i]
        @xy << {distance: d, height: h}

      end

      i = i + 1

    end

    render json: {data: @xy, config: {height: {min: min_h, max: max_h}, distance: {min: min_d, max: max_d}}}

  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index

    @reports = Dir.glob(Rails.root.join('public', 'reports','*')).map{|t| {name: t.split("/").last.split(".").first}}

    render json: {data: @reports}

  end
end

app/controllers/roads_controller.rb
class RoadsController < ApplicationController

  def index

    @roads = Dir.glob(Rails.root.join('public', 'roads','*')).map{|t| {name: t.split("/").last}}

    render json: {data: @roads}

  end

  def show


    @roads = Dir.glob(Rails.root.join('public', 'roads',params[:id],'*')).map{|t| {name: t.split("/").last}}

    render json: {data: @roads}

  end

  def gr


    table = Arrow::Table.load("#{Rails.root}/public/reports/#{params[:report_id]}.parquet")

    count = table.size

    @xy = []

    i = 1

    rh = table["restored_height"].to_a
    cd = table["current_distance"].to_a
    ci = table["cluster_id"].to_a

    min_h = nil
    max_h = nil

    min_d = nil
    max_d = nil

    while i < count - 1

      if rh[i].present? && cd[i].present? && ci[i] == "#{params[:id]}.csv"

        if (min_h.to_f > rh[i] && rh[i] != 0) || min_h == nil
          min_h = rh[i]
        end
        if (max_h.to_f < rh[i] && rh[i] != 0) || max_h == nil
          max_h = rh[i]
        end
        if (min_d.to_f > cd[i] && cd[i] != 0) || min_d == nil
          min_d = cd[i]
        end
        if (max_d.to_f < cd[i] && cd[i] != 0) || max_d == nil
          max_d = cd[i]
        end

        h = rh[i]
        d = cd[i]
        @xy << {distance: d, height: h}

      end
      i = i + 1
    end
    g = Gruff::Line.new(800,400)
    g.theme_pastel
    g.title = 'graphic'
    labels = {}
    @xy.each{|t| labels[t[:distance].to_s] = t[:distance]}
    g.labels = labels
    g.data params[:id].to_sym, @xy.map{|t| t[:height]}
    g.write('exciting.png')
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/roads_helper.rb
module RoadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsVuejs</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!--Google Font-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic|Material+Icons">
  <!--Font Awesome-->
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'main' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

app/views/roads/index.html.erb
<h1>Roads#index</h1>
<p>Find me in app/views/roads/index.html.erb</p>

app/views/roads/show.html.erb
<h1>Roads#show</h1>
<p>Find me in app/views/roads/show.html.erb</p>